name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: 1.36.0  # MSRV
          - rust: stable
          - rust: beta
          - rust: nightly
          - rust: nightly-i686-unknown-linux-gnu
          - rust: stable
            target: s390x-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Install packages
        if: matrix.rust == 'nightly-i686-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y gcc-multilib
      - name: Tests
        env:
          TARGET: ${{ matrix.target }}
        run: ./ci/script.sh
